- name: Setup LPOS stack on remote host(s)
  hosts: lpos
  become: true

  vars_files:
    - vars.yml

  roles:
    - geerlingguy.docker

  tasks:
    - include_tasks: tasks/ansiblerequirements.yml
    - include_tasks: tasks/mongodb.yml
    - include_tasks: tasks/lpos.yml
    - include_tasks: tasks/nginx.yml
    - include_tasks: tasks/haproxy.yml
    - include_tasks: tasks/monitoring.yml
      when: enable_monitoring | bool

    - name: prune docker images
      ansible.builtin.command: docker image prune -f
      register: prune_result
      changed_when: not prune_result.stdout.strip().endswith('0B')
