enable_monitoring: false

project_dir: '/opt/middleware/lpos'
mongodb_volume_dir: '/var/data/mongodb'
mongodb_backup_dir: '/var/backup'
haproxy_config_dir: '/etc/haproxy'
nginx_config_dir: '/etc/nginx/conf.d'

alpine_image: 'alpine'
mongodb_image: 'mongo:4.4'
nginx_image: 'nginx:alpine'
haproxy_image: 'haproxytech/haproxy-alpine:2.9.6'
dns_image: 'coredns/coredns:1.11.1'
dhcp_image: 'docker.cloudsmith.io/isc/docker/kea-dhcp4:2.5.7'
docker_exporter_image: 'shayanghani/container-exporter:latest'
mongodb_exporter_image: 'bitnami/mongodb-exporter:0.30.0'

lpos_service_name: 'lpos.service'
scanner_service_name: 'lpos-scanner.service'
nginx_service_name: 'lpos-fe.service'
haproxy_service_name: 'docker.haproxy.service'
mongodb_service_name: 'docker.mongodb.service'
docker_exporter_service_name: 'docker.docker-exporter.service'
mongodb_exporter_service_name: 'docker.mongodb-exporter.service'
